#!/usr/bin/env python3
"""
Univac-Aegis-bridge: Network Layer Matrix Processor
Parses 5x-stacked 36-bit analog matrix arrays and routes real-time 
containment over-rides based on calculated state-space transitions.
"""

import json
import math
import logging
from typing import Dict, List, Any

# Setup high-integrity hardware logging
logging.basicConfig(level=logging.INFO, format='[UNIVAC-CORE] %(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("MatrixProcessor")

class UnivacMatrixProcessor:
    def __init__(self):
        # Strict bitmask boundaries for 36-bit precision mapping
        self.WORD_36_MASK = (1 << 36) - 1  # 0x7FFFFFFFFF
        self.expected_keys = {"protocol", "version", "timestamp", "matrixState", "routingControls"}
        
    def decode_stacked_word(self, hex_word: str, stack_index: int) -> float:
        """
        Unpacks a 5x-stacked 36-bit word, strips structural offset, and recovers analog precision.
        Matches translation rules from light_equation_node.js.
        """
        try:
            # Parse hexadecimal token back to 64-bit integer space
            raw_val = int(hex_word, 16)
            
            # Reconstruct the bitwise shift applied during transmission
            stack_offset = stack_index << 32
            discrete_val = raw_val ^ stack_offset
            
            # Mask down to clean 36-bit space to eliminate transient bus noise
            cleaned_word = discrete_val & self.WORD_36_MASK
            
            # Normalize back into raw continuous floating-point value [0.0, 1.0]
            return float(cleaned_word) / float(self.WORD_36_MASK)
        except (ValueError, TypeError) as e:
            logger.error(f"Bit alignment failure on word {hex_word} at index {stack_index}: {str(e)}")
            return 0.0

    def verify_node_integrity(self, matrix_state: Dict[str, Any]) -> bool:
        """
        Validates the mathematical state boundary using an explicit continuous transition limit.
        Implements discrete filter checks tracking signal degradation.
        """
        confidence = matrix_state.get("filterConfidence", 0.0)
        integrity = matrix_state.get("integrityCheck", "DEGRADED")
        
        # Enforce hard bounded check threshold
        if integrity != "STABLE" or confidence <= 0.1:
            return False
            
        return True

    def process_incoming_packet(self, raw_json_string: str) -> Dict[str, Any]:
        """
        Ingests the live matrix stream, verifies configuration schema, 
        and routes physical actuation indicators.
        """
        try:
            packet = json.loads(raw_json_string)
        except json.JSONDecodeError:
            return {"status": "REJECTED", "reason": "MALFORMED_JSON_STREAM"}

        # Structural validation check against tracking scheme
        if not self.expected_keys.issubset(packet.keys()):
            return {"status": "REJECTED", "reason": "INVALID_UNIVAC_SCHEMA"}

        matrix_state = packet["matrixState"]
        routing_controls = packet["routingControls"]
        stacked_words = matrix_state.get("stackedWords36", [])

        if len(stacked_words) != 5:
            return {"status": "ERR_BUS_ALIGNMENT", "reason": "STACK_DEPTH_MISMATCH"}

        # Recover all 5 continuous-time precision tracks
        recovered_analog_signals = [
            self.decode_stacked_word(word, idx) for idx, word in enumerate(stacked_words)
        ]

        # Evaluate hardware health parameters
        is_healthy = self.verify_node_integrity(matrix_state)
        
        # Prepare action dispatch payload for bridge_network_router.py
        dispatch_directive = {
            "status": "PROCESSED",
            "timestamp": packet["timestamp"],
            "zone": packet.get("facilityZone", "UNKNOWN_ZONE"),
            "system_status": "INTEGRITY_VERIFIED" if is_healthy else "EMERGENCY_OVERRIDE_ACTIVE",
            "signals": recovered_analog_signals,
            "actions": {
                "isolation_gates": routing_controls.get("isolationGates", "OPEN"),
                "hvac_mode": routing_controls.get("hvacFlowMode", "NORMAL"),
                "brakes": routing_controls.get("elevatorBrakes", "MONITORING")
            }
        }

        logger.info(f"Successfully processed matrix chunk for zone: {dispatch_directive['zone']} -> Control Status: {dispatch_directive['actions']['isolation_gates']}")
        return dispatch_directive

# Pipeline integration loop for runtime execution testing
if __name__ == "__main__":
    # Test case matching the exact structure generated by the light_app interface
    sample_stream_packet = """
    {
        "protocol": "UNIVAC-MATRIX-STREAM",
        "version": "9.1.0-TACTICAL",
        "timestamp": "2026-06-29T07:45:00.000Z",
        "originNode": "AI_LIGHT_CRAWLER_PRIMARY",
        "facilityZone": "HOSPITAL_ICU_LEVEL_3",
        "matrixState": {
            "stackedWords36": ["0x00028F5C28", "0x10051EB851", "0x2007AE147A", "0x300A47AE14", "0x400CCCCCCCC"],
            "filterConfidence": 0.8854,
            "integrityCheck": "STABLE"
        },
        "routingControls": {
            "isolationGates": "LOCKED",
            "hvacFlowMode": "EXHAUST_ISOLATE",
            "elevatorBrakes": "MONITORING"
        }
    }
    """
    
    processor = UnivacMatrixProcessor()
    output_result = processor.process_incoming_packet(sample_stream_packet)
    print("\n--- MATRIX PROCESSED PIPELINE OUTPUT ---")
    print(json.dumps(output_result, indent=4))
