# File Name: weapon_serial_serializer.py
# Location: /src/network_layer/
# Subsystem: High-Speed Weapon Actuator Serial Protocol Layer

import math
from typing import Dict, Any, List

class WeaponSerialOutputSerializer:
    def __init__(self, manufacturer_code: str = "UNVC"):
        """
        Initializes the proprietary electronic warfare serial protocol encoder.
        manufacturer_code: 4-character identifier matching your hardware bus architecture.
        """
        self.prefix = f"P{manufacturer_code.upper()[:4]}EW"
        
        # Hardcoded ID mapping table to link string IDs to legacy numeric data buses
        self.mount_id_map = {
            'MAIN_5IN_MK45': 1,
            'AUX_76MM_MK75': 2,
            'PORT_CIWS_MK15': 3,
            'STBD_CIWS_MK15': 4
        }

    def _calculate_8bit_xor_checksum(self, payload: str) -> str:
        """Computes a standard industrial NMEA text string validation byte."""
        checksum = 0
        for char in payload:
            checksum ^= ord(char)
        return f"{checksum:02X}"

    def serialize_jammer_suppression_commands(self, allocation_matrices: List[dict]) -> List[bytes]:
        """
        Ingests the allocation array generated by the jammer engine, compiles
        the proprietary NMEA text strings, and outputs binary ASCII byte frames.
        """
        outbound_serial_packets = []
        
        for alloc in allocation_matrices:
            raw_id_string = alloc.get('mount_id', 'UNKNOWN')
            numeric_id = self.mount_id_map.get(raw_id_string, 99) # 99 = Unmapped general register
            
            ordered_az = alloc.get('ordered_azimuth_deg', 0.0)
            target_range = alloc.get('target_range_meters', 0.0)
            status_flag = alloc.get('allocation_status', 'NOMINAL')
            
            # Map system states into binary software interlock configuration bits
            override_bit = 1 if status_flag == "OVERRIDE_ACTIVE" else 0
            
            # Assemble the absolute text payload string (excluding leading '$' and trailing '*')
            payload = f"{self.prefix},{numeric_id},{ordered_az:.2f},{target_range:.1f},{override_bit}"
            
            # Append framing boundaries and hex checksum validations
            checksum_hex = self._calculate_8bit_xor_checksum(payload)
            final_sentence = f"${payload}*{checksum_hex}\r\n"
            
            # Convert directly into ASCII byte stream arrays to bypass python string translation latencies
            outbound_serial_packets.append(final_sentence.encode('ascii'))
            
        return outbound_serial_packets

# Local Verification and Loop Test Profile Environment
if __name__ == "__main__":
    serializer = WeaponSerialOutputSerializer(manufacturer_code="UNVC")
    
    # Mock data array matching your core allocation plant calculation output step
    mock_allocation_matrix = [
        {
            'mount_id': 'MAIN_5IN_MK45',
            'action': "MAINTAIN_PRIMARY_MISSION_ENGAGEMENT",
            'ordered_azimuth_deg': 12.0,
            'target_range_meters': 0.0,
            'allocation_status': "NOMINAL"
        },
        {
            'mount_id': 'AUX_76MM_MK75',
            'action': "ENGAGE_JAMMER_SUPPRESSION",
            'ordered_azimuth_deg': 45.32,
            'target_range_meters': 18450.0,
            'allocation_status': "OVERRIDE_ACTIVE"
        }
    ]
    
    print("SERIAL WEAPON PROTOCOL WIRE OUTPUT ENCODER:")
    print("=" * 75)
    
    binary_packets = serializer.serialize_jammer_suppression_commands(mock_allocation_matrix)
    
    for idx, packet in enumerate(binary_packets):
        print(f"Frame {idx} Wire Payload String:")
        print(packet.decode('ascii').strip())
