import logging
from datetime import datetime
from fastapi import FastAPI, Header, HTTPException, status
from pydantic import BaseModel, Field

# Configure basic logging for the Univac Aegis Bridge
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | [AEGIS CORE] | %(levelname)s | %(message)s"
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Univac Aegis Central Ingestion Bridge",
    description="Asynchronous telemetry receiver for distributed Fire-Watch edge nodes.",
    version="1.0.0"
)

# ---------------------------------------------------------
# DATA MODELS (Strictly matching the C# AegisPayload)
# ---------------------------------------------------------
class AegisTelemetryPayload(BaseModel):
    EventId: str = Field(..., description="Unique UUID generated by the edge node")
    Timestamp: datetime = Field(..., description="UTC timestamp of the hardware event")
    SourceNode: str = Field(..., description="Identifier of the edge device (e.g., Edwards-Axis-AX-01)")
    EventType: str = Field(..., description="Parsed event string (e.g., ALARM, TROUBLE, NORMAL)")
    SeverityLevel: int = Field(..., ge=0, le=10, description="Normalized threat level from 0 to 10")
    RawProtocolData: str = Field("", description="Hex string of the original panel bytes for forensic auditing")

# ---------------------------------------------------------
# API ENDPOINTS
# ---------------------------------------------------------
@app.post("/univac-aegis/ingest", status_code=status.HTTP_200_OK)
async def ingest_fire_telemetry(
    payload: AegisTelemetryPayload, 
    x_aegis_client: str = Header(None, description="Client authentication header")
):
    """
    Primary ingestion route for all remote Fire-Watch edge nodes.
    """
    # 1. Edge Authentication Validation
    if not x_aegis_client or not x_aegis_client.startswith("FireWatch-Node"):
        logger.warning(f"Rejected unauthorized payload connection attempt.")
        raise HTTPException(status_code=401, detail="Invalid or missing X-Aegis-Client header")

    # 2. Payload Processing Logic
    logger.info(f"Received payload {payload.EventId} from {payload.SourceNode}. Status: {payload.EventType}")

    # 3. Severity Matrix Routing
    if payload.SeverityLevel >= 8:
        await handle_critical_alarm(payload)
    elif payload.SeverityLevel >= 4:
        await handle_trouble_supervisory(payload)
    else:
        await handle_normal_telemetry(payload)

    return {"status": "ACK", "message": "Payload securely ingested by Univac Aegis Core"}

# ---------------------------------------------------------
# ASYNCHRONOUS WORKER FUNCTIONS
# ---------------------------------------------------------
async def handle_critical_alarm(payload: AegisTelemetryPayload):
    """
    Triggers when Severity is 8, 9, or 10 (Pre-Alarm / Alarm).
    Insert logic here to trigger facility evacuations, unlock doors, or notify command.
    """
    logger.critical(f"LIFE SAFETY INCIDENT: {payload.SourceNode} reports {payload.EventType}!")
    # Example: await dispatch_sip_voip_call(payload)
    # Example: await database_insert(payload)

async def handle_trouble_supervisory(payload: AegisTelemetryPayload):
    """
    Triggers when Severity is 4, 5, 6, or 7 (Trouble / Supervisory).
    Insert logic here to alert maintenance engineering of wire breaks or ground faults.
    """
    logger.error(f"HARDWARE FAULT: {payload.SourceNode} reports {payload.EventType}.")
    # Example: await dispatch_maintenance_email(payload)

async def handle_normal_telemetry(payload: AegisTelemetryPayload):
    """
    Triggers when Severity is 0 to 3 (Normal / Reset).
    Insert logic here to clear active UI dashboards or log the system reset.
    """
    logger.info(f"SYSTEM CLEAR: {payload.SourceNode} has returned to normal.")
    # Example: await clear_active_dashboard_alarms(payload.SourceNode)
